name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit random update
        run: |
          echo "$(date)" >> activity.txt
          git config --global user.email "gb5608@srmist.edu.in"
          git config --global user.name "ayerna"
          git add activity.txt
          git commit -m "Daily GitHub Action update"
          git push
